version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - db
    command: >
      sh -c "
        cp .env.example .env &&
        composer install &&
        php artisan key:generate &&
        php artisan migrate &&
        php-fpm
      "

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  node:
    image: node:18
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    entrypoint: ["npm"]
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
